[tool.poetry]
name = "finmaestro"
version = "0.1.0"
description = "A FastApi for the mighty Fin-Maestro by Dev_Finwiz."
authors = ["devfinwiz <devjuneja43@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.108.0"
uvicorn = "^0.25.0"
pydantic = "^2.5.3"
requests = "^2.31.0"
numpy = "^1.26.3"
pandas = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
